IsProjesi/IsProjesi/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static IsProjesi.MyAttributes;

namespace IsProjesi.Controllers
{
    [YetkiKontrol(YetkiAdi: "Satış")]
    public class SatisController : Controller
    {
        // GET: Satis
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Talep()
        {
            return View();
        }
        public ActionResult Talep_Talep()
        {
            return View();
        }
        public ActionResult Talep_MusteriAday()
        {
            return View();
        }
        public ActionResult Teklif()
        {
            return View();
        }
        public ActionResult Siparis()
        {
            return View();
        }



    }
}

IsProjesi/IsProjesi/Views/Satis/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<a href="@Url.Action("Talep","Satis")">Talep</a>  /
<a href="@Url.Action("Teklif","Satis")">Teklif</a>/
<a href="@Url.Action("Siparis","Satis")"> Sipariş</a> /

IsProjesi/IsProjesi/Views/Satis/Siparis.cshtml
@{
    ViewBag.Title = "Siparis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Siparis</h2>

IsProjesi/IsProjesi/Views/Satis/Talep.cshtml
@{
    ViewBag.Title = "Talep";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">
    <div class="row">

        <div class="col-md-6">
            <div class="panel panel-body text-center">
                <a href="@Url.Action("Talep_Talep","Satis")">


                    <p class="text-muted content-group-sm"><i class="icon-3x icon-file-text text-info"></i></p>
                    <h5 class="no-margin text-semibold">Talep</h5>

                </a>
            </div>

        </div>


        <div class="col-md-6">
            <div class="panel panel-body text-center">
                <a href="@Url.Action("Talep_MusteriAday","Satis")">

                    <p class="text-muted content-group-sm"><i class="icon-3x icon-people text-info"></i></p>
                    <h5 class="no-margin text-semibold">Müşteri Aday</h5>

                </a>
            </div>

        </div>


    </div>

</div>

IsProjesi/IsProjesi/Views/Satis/Talep_MusteriAday.cshtml
@{
    ViewBag.Title = "Talep_MusteriAday";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Talep_MusteriAday</h2>

IsProjesi/IsProjesi/Views/Satis/Talep_Talep.cshtml
@{
    ViewBag.Title = "Talep_Talep";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Talep_Talep</h2>

IsProjesi/IsProjesi/Views/Satis/Teklif.cshtml
@{
    ViewBag.Title = "Teklif";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Teklif</h2>