IsProjesi/IsProjesi/Models/Tedarikci.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikci
    {
        public Tedarikci()
        {
            this.Evrak = new HashSet<Evrak>();
            this.GiderFatura = new HashSet<GiderFatura>();
            this.Not = new HashSet<Not>();
            this.SatinAlmaBankaHesapBilgisi = new HashSet<SatinAlmaBankaHesapBilgisi>();
            this.SatinAlmaTeklif = new HashSet<SatinAlmaTeklif>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ilID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public Nullable<int> TedarikTurID { get; set; }
        public string FirmaAdi { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Yetkili { get; set; }
        public string CepTel { get; set; }
        public string Adres { get; set; }
        public string VergiNumarası { get; set; }
        public string VergiDairesi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string FaturaUnvan { get; set; }
        public Nullable<int> Durumu { get; set; }
    
        public virtual ICollection<Evrak> Evrak { get; set; }
        public virtual ICollection<GiderFatura> GiderFatura { get; set; }
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual ICollection<Not> Not { get; set; }
        public virtual ICollection<SatinAlmaBankaHesapBilgisi> SatinAlmaBankaHesapBilgisi { get; set; }
        public virtual ICollection<SatinAlmaTeklif> SatinAlmaTeklif { get; set; }
        public virtual TedarikciTur TedarikciTur { get; set; }
    }
}

IsProjesi/IsProjesi/Models/TedarikciTur.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikciTur
    {
        public TedarikciTur()
        {
            this.Tedarikci = new HashSet<Tedarikci>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<Tedarikci> Tedarikci { get; set; }
    }
}

IsProjesi/IsProjesi/Controllers/SatinAlmaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using IsProjesi.Models;
using static IsProjesi.MyAttributes;


namespace IsProjesi.Controllers
{
    [YetkiKontrol(YetkiAdi: "Satın Alma")]
    public class SatinAlmaController : Controller
    {
        // GET: SatinAlma





        TedarikciTurBLL tedarikciTurBLL = new TedarikciTurBLL();
        TedarikciTur tedarikciTur = new TedarikciTur();

        TedarikciBLL tedarikciBLL = new TedarikciBLL();
        Tedarikci tedarikci = new Tedarikci();


        SatinAlmaTeklifBLL satinAlmaTeklifBLL = new SatinAlmaTeklifBLL();
        SatinAlmaTeklif satinAlmaTeklif = new SatinAlmaTeklif();


        SatinAlmaTeklif_DetayBLL satinAlmaTeklif_DetayBLL = new SatinAlmaTeklif_DetayBLL();



        public ActionResult Index()
        {
            return View();
        }
        //tedarikçi turdur 
        public ActionResult Kategori()
        {
            return View();
        }

        public ActionResult TedarikciTurEkleGuncelle(int ID = 0)
        {

            tedarikciTur = tedarikciTurBLL.GetById(ID);
            return View(tedarikciTur);
        }
        public ActionResult Tedarikci()
        {
            List<Tedarikci> tedarikciList = tedarikciBLL.GetAll().ToList();
            return View(tedarikciList);
        }
        public ActionResult TedarikciEkleGuncelle(int ID = 0)
        {
            tedarikci = tedarikciBLL.GetById(ID);
            return View(tedarikci);
        }
        public ActionResult illereGoreilceleriGetir(int Idil)
        {
            List<SelectListItem> ilceAdlari = new List<SelectListItem>();
            if (Idil != 0)
            {
                var ilceler = YardimciClass.ilceleriListele(Idil);
                ilceler.ForEach(x =>
                {
                    ilceAdlari.Add(new SelectListItem { Text = x.IlceAdi, Value = x.ID.ToString() });
                });
            }
            return Json(ilceAdlari, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Teklif()
        {

            var satinAlmaTeklifList = satinAlmaTeklifBLL.GetAll().ToList();

            return View(satinAlmaTeklifList);
        }

        public ActionResult TeklifEkleGuncelle(int ID = 0)
        {
            satinAlmaTeklif = satinAlmaTeklifBLL.GetById(ID);



            return View(satinAlmaTeklif);
        }

        public ActionResult TeklifVeDetaylar(int ID)
        {
            satinAlmaTeklif = satinAlmaTeklifBLL.GetById(ID);
            List<SatinAlmaTeklif_Detay> list = satinAlmaTeklif_DetayBLL.GetLazyLoading(x => x.SatinAlmaTeklifID == satinAlmaTeklif.ID).ToList();

            return PartialView(list);

            //satinAlmaTeklif = satinAlmaTeklifBLL.GetById(ID);
            //List<SatinAlmaTeklif_Detay> list = satinAlmaTeklif_DetayBLL.GetLazyLoading(x => x.SatinAlmaTeklifID == satinAlmaTeklif.ID).ToList();

            //return Json(list.Select(s => s.KalemAdi), JsonRequestBehavior.AllowGet);

        }
        //var satinAlmaTeklif_DetayListesi = new List<SatinAlmaTeklif_Detay>();
        //satinAlmaTeklif = satinAlmaTeklifBLL.GetById(ID);
        //foreach (var item in satinAlmaTeklif.SatinAlmaTeklif_Detay)
        //{
        //    satinAlmaTeklif_DetayListesi.Add(item);
        //}
        //return Json(satinAlmaTeklif_DetayListesi.ToList(),JsonRequestBehavior.AllowGet);

        //public JsonResult TekliflerinDetayListesi(int ID)
        //{

        //    return Json(GetArticlesByCategory(ID));
        //}
        //public IQueryable<ArticleTitle> GetArticlesByCategory(int id)
        //{
        //    inotr_sistemEntities de = new inotr_sistemEntities();
        //    return (de.SatinAlmaTeklif_Detay.Where(a => a.SatinAlmaTeklif.ID == id)

        //      .Select(a => new ArticleTitle
        //      {
        //          Aciklama = a.Aciklama,
        //          Head = a.KalemAdi,
        //      }))
        //      .AsQueryable();
        //}

        //public class ArticleTitle
        //{
        //    public string Aciklama { get; set; }
        //    public string Head { get; set; }
        //}







        //inotr_sistemEntities entity = new inotr_sistemEntities();
        //var result = from c in entity.SatinAlmaTeklif.Include("SatinAlmaTeklif_Detay")
        //             where c.ID == ID
        //             select new
        //             {
        //                 c.GenelToplamTutar,
        //                 c.SatinAlmaTeklif_Detay.Count,
        //             };


        //    return Json(result.ToList(), JsonRequestBehavior.AllowGet);

        //var satinAlmaTeklif_DetayListesi = new List<SatinAlmaTeklif_Detay>();
        //satinAlmaTeklif = satinAlmaTeklifBLL.GetById(ID);
        //foreach (var item in satinAlmaTeklif.SatinAlmaTeklif_Detay)
        //{
        //    satinAlmaTeklif_DetayListesi.Add(item);
        //}
        //return Json(satinAlmaTeklif_DetayListesi.ToList(),JsonRequestBehavior.AllowGet);

        //[HttpPut]
        //public JsonResult TeklifGuncelle(SatinAlmaTeklif teklif,int ID)
        //{

        //    teklif.Tarih = DateTime.Now;
        //    var teklifTutarDurum = 0;
        //    if (teklif.Tutar>0)
        //    {
        //        if (teklif.KdvOran==1)
        //        {
        //            teklif.ToplamTutar = teklif.Tutar - teklif.Indirim ;
        //        }
        //        else
        //        {
        //            teklif.ToplamTutar = teklif.Tutar - teklif.Indirim - (teklif.Tutar * teklif.KdvOran)/100;
        //        }  
        //    }

        //    if (teklif.ToplamTutar>0)
        //    {
        //        satinAlmaTeklifBLL.InsertOrUpdate(teklif, ID);
        //        teklifTutarDurum = 1;
        //    }

        //    return Json(teklifTutarDurum, JsonRequestBehavior.AllowGet);
        //}
        //[HttpPost]
        //public JsonResult TeklifEkle(SatinAlmaTeklif teklif)
        //{
        //    teklif.Tarih = DateTime.Now;
        //    var teklifTutarDurum = 0;
        //    if (teklif.Tutar > 0)
        //    {
        //        if (teklif.KdvOran == 1)
        //        {
        //            teklif.ToplamTutar = teklif.Tutar - teklif.Indirim;
        //        }
        //        else
        //        {
        //            teklif.ToplamTutar = teklif.Tutar - teklif.Indirim - (teklif.Tutar * teklif.KdvOran) / 100;
        //        }
        //    }
        //    if (teklif.ToplamTutar>0)
        //    {
        //        satinAlmaTeklifBLL.Insert(teklif);
        //        teklifTutarDurum = 1;
        //    }        
        //    return Json(teklifTutarDurum,JsonRequestBehavior.AllowGet);
        //}

        public ActionResult Siparis()
        {
            return View();
        }
    }
}

IsProjesi/IsProjesi/Views/SatinAlma/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<a href="@Url.Action("Kategori","SatinAlma")">  Kategoriler</a>  /
<a href="@Url.Action("Tedarikci","SatinAlma")">Tedarikçiler</a>/

<a href="@Url.Action("Teklif","SatinAlma")">Teklif</a> /
<a href="@Url.Action("Siparis","SatinAlma")">Sipariş</a>

IsProjesi/IsProjesi/Views/SatinAlma/Kategori.cshtml
@{
    ViewBag.Title = "Kategori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/InotrScript/SatinAlma.js"></script>


<div class="content-wrapper">
    <div class="panel panel-flat">
        <div class="panel-heading">




            <a href="@Url.Action("TedarikciTurEkleGuncelle","SatinAlma")">
                <input type="button" name="name" value="Yeni Tedarikçi Tür  Ekle" class="btn btn-primary" />
            </a>


            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>
        <table class="table datatable-responsive-control-right">
            <thead>
                <tr>
                    <th>Tedarikçi Tür Adı</th>

                    <th></th>
                </tr>
            </thead>
            <tbody id="KategoriTedarikci"></tbody>
        </table>
    </div>
</div>

IsProjesi/IsProjesi/Views/SatinAlma/Siparis.cshtml
@{
    ViewBag.Title = "Siparis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Siparis</h2>

IsProjesi/IsProjesi/Views/SatinAlma/Tedarikci.cshtml
@{
    ViewBag.Title = "Tedarikci";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model List<Tedarikci>


<script src="~/Scripts/InotrScript/SatinAlma.js"></script>



<div class="content-wrapper">
    <div class="panel panel-flat">
        <div class="panel-heading">




            <a href="@Url.Action("TedarikciEkleGuncelle","SatinAlma")">
                <input type="button" name="name" value="Yeni Tedarikçi  Ekle" class="btn btn-primary" />
            </a>


            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>
        <table class="table datatable-responsive-control-right">
            <thead>
                <tr>
                    <th>Firma Adı</th>
                    <th>Kategori Adı</th>
                    <th>Yetkili</th>
                    <th>Email</th>
                    <th>Telefon</th>
                    <th>Durumu</th>
                    <th>Tarih</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {


                        <tr>
                            <td>@item.FirmaAdi</td>



                            <td>
                            
                               @item.TedarikciTur.Adi
                            </td>
                            <td>@item.Yetkili</td>
                            <td>@item.Email</td>
                            <td>@item.Telefon</td>
                             @if (item.Durumu == 1)
                             {

                                <td><span class="label label-success">Aktif</span></td>


                             }
                             else
                             {
                                <td><span class="label label-danger">Pasif</span></td>
                               
                             }


                            <td>@item.Tarih.</td>
                            <td class="text-center">
                                <ul class="icons-list">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-menu9"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li onclick="TedarikGuncelleSayfasiniAc(@item.ID)"><a href="#"><i class="btn btn-primary"></i>Düzenle</a></li>

                                        </ul>
                                    </li>
                                </ul>
                            </td>
                            <td></td>
                        </tr>
                


                }
            </tbody>
        </table>
    </div>
</div>

IsProjesi/IsProjesi/Views/SatinAlma/TedarikciEkleGuncelle.cshtml
@{
    ViewBag.Title = "TedarikciEkleGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@{




    ilBLL ilbll = new ilBLL();
    ilceBLL ilcebll = new ilceBLL();
    TedarikciTurBLL tedarikciTurBLL = new TedarikciTurBLL();
    List<il> ilListe = ilbll.GetAll().ToList();
    List<ilce> ilceListe = ilcebll.GetAll().ToList();

    List<TedarikciTur> tedarikTurList = tedarikciTurBLL.GetAll().ToList();


   




}

@model Tedarikci



<script src="~/Scripts/InotrScript/SatinAlma.js"></script>


<div class="content-wrapper">
    <div class="page-header panel" style="padding-bottom: 0;">
        <div class="page-header-content">
            <div class="page-title">
                <h5>
                    <a href="#" class="btn bg-grey btn-icon btn-rounded btn-xs mr-10"><i class="" icon-arrow-left13"></i></a><span class="text-semibold">Tedarik Bilgisi</span>

                </h5>
            </div>
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="FirmaAdi">Firma Adı:</label>
                        <input type="text" class="form-control" id="FirmaAdi" value="@Model.FirmaAdi" placeholder="Firma Adı">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Tedarik Tür">Tedarik Tür:</label>

                        <select id="tedarikTurListe" class="form-control">
                            @foreach (TedarikciTur item in tedarikTurList)
                            {
                                <option value="@item.ID" @(Model.TedarikTurID == item.ID ? "selected" : "")>@item.Adi</option>
                            }

                        </select>

                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Email">Email:</label>
                        <input type="text" class="form-control" id="Email" value="@Model.Email" placeholder="Email">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Telefon">Telefon:</label>
                        <input type="text" class="form-control" id="Telefon" value="@Model.Telefon" placeholder="Telefon">
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Fax">Fax:</label>
                        <input type="text" class="form-control" id="Fax" value="@Model.Fax" placeholder="Fax">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="baslik">Cep Telefon:</label>
                        <input type="text" class="form-control" id="CepTel" value="@Model.CepTel" placeholder="cep telefon">
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Yetkili">Yetkili:</label>
                        <input type="text" class="form-control" id="Yetkili" value="@Model.Yetkili" placeholder="Yetkili">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="FaturaUnvan">Fatura Ünvan:</label>
                        <input type="text" class="form-control" id="FaturaUnvan" value="@Model.FaturaUnvan" placeholder="Fatura Ünvan">
                    </div>
                </div>

            </div>



            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="VergiNumarası">Vergi Numarası:</label>
                        <input type="text" class="form-control" id="VergiNumarası" value="@Model.VergiNumarası" placeholder="vergi numarası">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="VergiDairesi">Vergi Dairesi:</label>
                        <input type="text" class="form-control" id="VergiDairesi" value="@Model.VergiDairesi" placeholder="vergi dairesi">
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">

                        <label for="il">İl:</label>
                        <select id="illerID" class="form-control">
                            @foreach (il item in ilListe)
                            {
                                <option value="@item.ID" @(Model.ilID == item.ID ? "selected" : "")>@item.Adi</option>
                            }

                        </select>

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="fax">İlçe:</label>
                        <select id="ilceListesiID" class="form-control">
                            @foreach (ilce item in ilceListe)
                            {
                                <option value="@item.ID" @(Model.ilceID == item.ID ? "selected" : "")>@item.IlceAdi</option>
                            }

                        </select>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="Adres">Durum:</label>
                        <select class="form-control" id="Durumu">
                            @if (Model.ID == 0)
                            {
                                <option value="">Durumu Seçiniz</option>
                            }
                            <option value="1" @(Model.Durumu == 1 && Model.ID > 0 ? "selected" : "" )>Aktif</option>
                            <option value="0" @(Model.Durumu == 0 && Model.ID > 0 ? "selected" : "" )>Pasif</option>
                           
                        </select>



                   
                     
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="Adres">Adres:</label>
                        <input type="text" class="form-control" id="Adres" value="@Model.Adres" placeholder="Adres">
                    </div>
                </div>

            </div>
            <div class="row">
                @if (Model.ID == 0)
                {
                    <div class="col-md-12">

                        <a class="btn btn-success pull-right" onclick="TedarikEkle()">Ekle <i class="icon-checkmark4 position-right"></i></a>

                    </div>
                }
                else
                {
                    <div class="col-md-12">
                        <a class="btn btn-success pull-right" href="javascript:;" onclick="TedarikGuncelle(@Model.ID)">Kaydet <i class="icon-checkmark4 position-right"></i></a>
                    </div>
                }


            </div>

           



        </div>

    </div>
</div>

IsProjesi/IsProjesi/Views/SatinAlma/TedarikciTur.cshtml
@{
    ViewBag.Title = "Kategori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="~/Scripts/InotrScript/SatinAlma.js"></script>


<div class="content-wrapper">
    <div class="panel panel-flat">
        <div class="panel-heading">


           

            <a href="@Url.Action("TedarikciTurEkleGuncelle","SatinAlma")">
                <input type="button" name="name" value="Yeni Kategori  Ekle" class="btn btn-primary" />
            </a>


            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>
        <table class="table datatable-responsive-control-right">
            <thead>
                <tr>
                    <th>Kategori Adı</th>
                   
                    <th></th>
                </tr>
            </thead>
            <tbody id="KategoriTedarikci"></tbody>
        </table>
    </div>
</div>

IsProjesi/IsProjesi/Views/SatinAlma/TedarikciTurEkleGuncelle.cshtml
@{
    ViewBag.Title = "TedarikciKategoriEkleGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<script src="~/Scripts/InotrScript/SatinAlma.js"></script>


@model TedarikciTur

<div class="content-wrapper">
    <div class="page-header panel" style="padding-bottom: 0;">
        <div class="page-header-content">
            <div class="page-title">
                <h5>
                    <a href="#" class="btn bg-grey btn-icon btn-rounded btn-xs mr-10"><i class="" icon-arrow-left13"></i></a><span class="text-semibold">Tedarik Kategori Bilgisi</span>

                </h5>
            </div>
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="baslik">Kategori Adı:</label>
                        <input type="text" class="form-control" id="Adi" value="@Model.Adi" placeholder="Adı">
                    </div>
                </div>

            </div>






            <div class="row">
                @if (Model.ID == 0)
                {
                    <div class="col-md-12">
                        <a class="btn btn-success pull-right" onclick="TedarikKategoriTurEkle()">Ekle <i class="icon-checkmark4 position-right"></i></a>
                    </div>
                }
                else
                {
                    <div class="col-md-12">
                        <a class="btn btn-success pull-right" href="javascript:;" onclick="TedarikKategoriTurGuncelle(@Model.ID)">Kaydet <i class="icon-checkmark4 position-right"></i></a>
                    </div>
                }


            </div>

           



        </div>

    </div>
</div>

IsProjesi/IsProjesi/Views/SatinAlma/Teklif.cshtml
@{
    ViewBag.Title = "Teklif";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



    @model List<SatinAlmaTeklif>

 



<script src="~/Scripts/InotrScript/SatinAlma.js"></script>
<div class="content-wrapper">
    <div class="panel panel-flat">
        <div class="panel-heading">




            <a href="@Url.Action("TeklifEkleGuncelle","SatinAlma")">
                <input type="button" name="name" value="Yeni Teklif Ekle" class="btn btn-primary" />
            </a>


            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>
        <table class="table datatable-responsive-control-right">
            <thead>
                <tr>
                    <th>Tedarikçi  Adı</th>
                    <th>Toplam Tutar</th>
                    <th>Tarih</th>
                    <th>Teklif Tarih</th>
                    <th>Durum</th>                  
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>@item.Tedarikci.FirmaAdi</td>
                        <td>@item.ToplamTutar</td>
                        <td>@item.Tarih</td>
                        <td>@item.TeklifTarih</td>
                   
                        @if (item.Durum == 0)
                        {

                            <td><span class="label label-warning">Beklemede</span></td>


                        }
                        else if(item.Durum==1)
                        {
                            <td><span class="label label-success">Onaylandı</span></td>

                        }
                        else
                        {
                            <td><span class="label label-danger">İptal</span></td>

                        }

                        <td class="text-center">
                            <ul class="icons-list">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-menu9"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li onclick="TeklifGuncelleSayfasiniAc(@item.ID)"><a href="#"><i class="btn btn-primary"></i>Düzenle</a></li>
                                        
                                    </ul>
                                </li>
                            </ul>
                        </td>
                        <td></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

IsProjesi/IsProjesi/Views/SatinAlma/TeklifVeDetaylar.cshtml
@model List<SatinAlmaTeklif_Detay>

@{

    double toplam = 0;
}
<div>
    @foreach (var item in Model)
    {




        double? d2 = toplam as double?;


       d2 = item.Indirim + item.BirimFiyat + item.Adet;



    }
</div>
<input type="text" id="topindirim" value="@toplam" />