IsProjesi/IsProjesi/Controllers/TasarimAyarlariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static IsProjesi.MyAttributes;

namespace IsProjesi.Controllers
{
    [YetkiKontrol(YetkiAdi: "Tasarım Ayarları")]
    public class TasarimAyarlariController : Controller
    {
        // GET: TasarimAyarlari
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GenelTasarim()
        {
            return View();
        }
        public ActionResult FaturaAltBilgi()
        {
            return View();
        }
        public ActionResult SiparisAltBilgi()
        {
            return View();
        }
        public ActionResult SiparisUstBilgi()
        {
            return View();
        }
        public ActionResult EPostaTasarimi()
        {
            return View();
        }
        public ActionResult FaturaYazdırma()
        {
            return View();
        }

    }
}

IsProjesi/IsProjesi/Views/TasarimAyarlari/EPostaTasarimi.cshtml
@{
    ViewBag.Title = "EPostaTasarimi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EPostaTasarimi</h2>

IsProjesi/IsProjesi/Views/TasarimAyarlari/FaturaAltBilgi.cshtml
@{
    ViewBag.Title = "FaturaAltBilgi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FaturaAltBilgi</h2>

IsProjesi/IsProjesi/Views/TasarimAyarlari/FaturaYazdırma.cshtml
@{
    ViewBag.Title = "FaturaYazdırma";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FaturaYazdırma</h2>

IsProjesi/IsProjesi/Views/TasarimAyarlari/GenelTasarim.cshtml
@{
    ViewBag.Title = "GenelTasarim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GenelTasarim</h2>

IsProjesi/IsProjesi/Views/TasarimAyarlari/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a href="@Url.Action("GenelTasarim","TasarimAyarlari")">Genel Tasarım</a>  /
<a href="@Url.Action("FaturaAltBilgi","TasarimAyarlari")">Fatura Alt Bilgi</a>/
<a href="@Url.Action("SiparisAltBilgi","TasarimAyarlari")">Sipariş Alt Bilgi</a>  /
<a href="@Url.Action("SiparisUstBilgi","TasarimAyarlari")">Sipariş Üst Bilgi</a>/
<a href="@Url.Action("EPostaTasarimi","TasarimAyarlari")">E Posta Tasarımı</a>  /
<a href="@Url.Action("FaturaYazdırma","TasarimAyarlari")">Fatura Yazdırma</a>

IsProjesi/IsProjesi/Views/TasarimAyarlari/SiparisAltBilgi.cshtml
@{
    ViewBag.Title = "SiparisAltBilgi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SiparisAltBilgi</h2>

IsProjesi/IsProjesi/Views/TasarimAyarlari/SiparisUstBilgi.cshtml
@{
    ViewBag.Title = "SiparisUstBilgi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SiparisUstBilgi</h2>