IsProjesi/IsProjesi/Models/StokHareketleri.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareketleri
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> StokTip { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> StokAdet { get; set; }
    
        public virtual UrunHizmet UrunHizmet { get; set; }
    }
}

IsProjesi/IsProjesi/Models/UrunHizmet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunHizmet
    {
        public UrunHizmet()
        {
            this.Isler = new HashSet<Isler>();
            this.StokHareketleri = new HashSet<StokHareketleri>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KdvID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> MiktarTurD { get; set; }
        public Nullable<int> StokDurum { get; set; }
        public Nullable<int> UrunTipID { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string UrunKodu { get; set; }
        public Nullable<int> StokAdetFinal { get; set; }
        public Nullable<int> DonguselAralik { get; set; }
        public Nullable<double> DonguselFiyat { get; set; }
        public string UrunIcerik { get; set; }
        public string UrunResim { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual Kdv Kdv { get; set; }
        public virtual MiktarTur MiktarTur { get; set; }
        public virtual ICollection<StokHareketleri> StokHareketleri { get; set; }
        public virtual UrunHizmetKategori UrunHizmetKategori { get; set; }
    }
}

IsProjesi/IsProjesi/Controllers/UrunHizmetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IsProjesi.Models;
using static IsProjesi.MyAttributes;

namespace IsProjesi.Controllers
{
    //[YetkiKontrol(YetkiAdi: "Ürün ve Hizmetler")]
    public class UrunHizmetController : Controller
    {


        UrunHizmetKategoriBLL urunHizmetKategoriBLL = new UrunHizmetKategoriBLL();
        UrunHizmetBLL urunHizmetBLL = new UrunHizmetBLL();
        //UrunHizmetKategori urunHizmetKategori = new UrunHizmetKategori();




        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Kategoriler()
        {
          
            List<UrunHizmetKategori> UrunHizmetKategoriList = urunHizmetKategoriBLL.GetAll().ToList();
            return View(UrunHizmetKategoriList);
     
        }

        public ActionResult KategoriEkleGuncelle(int ID=0)
        {
          var kategori= urunHizmetKategoriBLL.GetById(ID);
            return View(kategori);
        }


        public ActionResult UrunEkleGuncelle(int ID)
        {
            var urun = urunHizmetBLL.GetById(ID);
            return View(urun);
        }
        public ActionResult KategoriEkle(UrunHizmetKategori urunHizmetKategori)
        {

         
                urunHizmetKategori.Tarih = DateTime.Now;
                urunHizmetKategoriBLL.Insert(urunHizmetKategori);
               
         

            return Json(0);
        }
        public ActionResult KategoriGuncelle(UrunHizmetKategori urunHizmetKategori)
        {

            urunHizmetKategori.Tarih = DateTime.Now;
            urunHizmetKategoriBLL.Update(urunHizmetKategori);
            return Json(0);

        }


        public ActionResult Urunler()
        {
            List<UrunHizmet> urunHizmetList = urunHizmetBLL.GetAll().ToList();

            return View(urunHizmetList);
        }
        public ActionResult StokHareketleri()
        {
            return View();
        }
    }
}

IsProjesi/IsProjesi/Views/UrunHizmet/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>



<a href="@Url.Action("Urunler","UrunHizmet")">Urunler-Hizmetler</a>  /
<a href="@Url.Action("Kategoriler","UrunHizmet")">Kategoriler</a>/

<a href="@Url.Action("StokHareketleri","UrunHizmet")">Stok Hareketleri</a>/

IsProjesi/IsProjesi/Views/UrunHizmet/KategoriEkleGuncelle.cshtml
@{
    ViewBag.Title = "KategoriEkleGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";

    UrunHizmetKategoriBLL urunHizmetKategoriBLL = new UrunHizmetKategoriBLL();
    List<UrunHizmetKategori> urunHizmetKategoriListesi = urunHizmetKategoriBLL.GetAll().ToList();


}

<script src="~/Scripts/InotrScript/UrunHizmet.js"></script>


<div class="content-wrapper">
    @model UrunHizmetKategori

    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title" id="pagetitle"><span>Ürün Kategori Yönetimi </span></h5>

            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a href="@Url.Action("Kategoriler","UrunHizmet")" class="btn btn-default btn-xs"><b><i class="icon-backward"></i></b>&nbsp;GERİ</a></li>
                    
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>

            <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="Ad">Başlık:</label>
                        <input type="text" class="form-control" id="Ad" placeholder="Ad" value="@Model.Ad">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Bağlı Olduğu Kategori</label>
                        <select class="form-control" id="UstID">
                            <option value="0">Üst Kategori </option>
                            @foreach (var item in urunHizmetKategoriListesi)
                            {
                                <option value="@item.ID" @(Model.UstID == item.ID ? "selected" : "")>@item.Ad</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                @if (Model.ID == 0)
                {
                    <div class="col-md-12">

                        <a class="btn btn-success pull-right" onclick="KategoriEkle()">Ekle <i class="icon-checkmark4 position-right"></i></a>

                    </div>
                }
                else
                {
                    <div class="col-md-12">
                        <a class="btn btn-success pull-right" href="javascript:;" onclick="KategoriGuncelle(@Model.ID)">Kaydet <i class="icon-checkmark4 position-right"></i></a>
                    </div>
                }


            </div>

        </div>
    </div>
</div>

IsProjesi/IsProjesi/Views/UrunHizmet/Kategoriler.cshtml
@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model List<UrunHizmetKategori>


<div class="content-wrapper">
    <div class="panel panel-flat">
        <div class="panel-heading">

            <h5>

                <a href="urunhizmet_modul.aspx" class=""></a><span class="">Ürün &amp; Hizmet Kategorileri</span>


            </h5>

            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a href="?" class="btn btn-default btn-xs"><b><i class="icon-backward"></i></b>&nbsp;GERİ</a></li>
                    <li><a href="@Url.Action("KategoriEkleGuncelle","UrunHizmet")" class="btn btn-default btn-xs"><b><i class=" icon-plus-circle2"></i></b>&nbsp;YENİ KATEGORİ</a></li>
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>

            <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
        </div>

        <div class="panel-body">
            <div id="tablekategori_wrapper" class="dataTables_wrapper no-footer">
                <div class="datatable-scroll">
                    <table id="tablekategori" class="table datatable-basic table-hover no-footer dataTable" role="grid" aria-describedby="tablekategori_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="tablekategori" rowspan="1" colspan="1" aria-label="ID: activate to sort column descending" style="width: 45px;" aria-sort="ascending">ID</th>
                                <th class="sorting_asc" tabindex="0" aria-controls="tablekategori" rowspan="1" colspan="1" aria-label="Başlık: activate to sort column descending" style="width: 45px;" aria-sort="ascending">Başlık</th>
                                <th class="sorting" tabindex="0" aria-controls="tablekategori" rowspan="1" colspan="1" aria-label="Üst Kategori: activate to sort column ascending" style="width: 85px;">Üst Kategori</th>

                                <th class="sorting" tabindex="0" aria-controls="tablekategori" rowspan="1" colspan="1" aria-label="Eklenme Tarihi: activate to sort column ascending" style="width: 101px;">Eklenme Tarihi</th>
                                <th class="text-center sorting" tabindex="0" aria-controls="tablekategori" rowspan="1" colspan="1" aria-label="İşlemler: activate to sort column ascending" style="width: 57px;">İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {


                                <tr role="row" class="odd">
                                    <td>@item.ID</td>
                                    <td style="" class="sorting_1">
                                        <span style="display:none">1500- </span>
                                        <span style="font-weight:bold">@item.Ad</span>
                                    </td>
                                    @if (item.UstID > 0)
                                    {
                                        UrunHizmetKategori ustKategori = new UrunHizmetKategori();
                                        UrunHizmetKategoriBLL KategoriBLL = new UrunHizmetKategoriBLL();
                                        ustKategori = KategoriBLL.GetById(item.UstID);
                                        <td>@ustKategori.Ad</td>
                                    }
                                    else
                                    {
                                        <td>Üst Kategorisi Yok</td>
                                    }


                                    <td>@item.Tarih</td>
                                    <td class="text-center">
                                        <ul class="icons-list">
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                    <i class="icon-menu9"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-right">
                                                    <li onclick="KategoriGuncellemeSayfasiniAc(@item.ID)"><a href="#"><i class="btn btn-primary"></i>Düzenle</a></li>
                                                    <li onclick="UrunHizmetKategoriSil(@item.ID)"><a href="#"><i class="btn btn-danger"></i>Sil</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>

            </div>


        </div>




    </div>



</div>
<script src="~/Scripts/InotrScript/UrunHizmet.js"></script>
<script>
    $(document).ready(function () {
        $('#tablekategori').DataTable({



            "language": {
                "sDecimal": ",",
                "sEmptyTable": "Tabloda herhangi bir veri mevcut değil",
                "sInfo": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
                "sInfoEmpty": "Kayıt yok",
                "sInfoFiltered": "(_MAX_ kayıt içerisinden bulunan)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "Sayfada _MENU_ kayıt göster",
                "sLoadingRecords": "Yükleniyor...",
                "sProcessing": "İşleniyor...",
                "sSearch": "Ara:",
                "sZeroRecords": "Eşleşen kayıt bulunamadı",
                "oPaginate": {
                    "sFirst": "İlk",
                    "sLast": "Son",
                    "sNext": "Sonraki",
                    "sPrevious": "Önceki"
                },
                "oAria": {
                    "sSortAscending": ": artan sütun sıralamasını aktifleştir",
                    "sSortDescending": ": azalan sütun sıralamasını aktifleştir"
                }
            }, buttons: [
      'copy', 'pdf', 'excel', 'csv'
            ]


        });
    });
</script>
























@*<div class="content-wrapper">
        <div class="panel panel-flat">
            <div class="panel-heading">
                @*<a href="/Yetki/EkleGuncelle">
                        <input type="button" name="name" value="Yeni Kategori  Ekle" class="btn btn-primary">
                    </a>


    <div class="heading-elements">
        <ul class="icons-list">
            <li><a data-action="collapse"></a></li>
            <li><a data-action="reload"></a></li>
            <li><a data-action="close"></a></li>
        </ul>
    </div>
            </div>
    <table class="table datatable-responsive-control-right">
        <thead>
            <tr>
                <th>Adı</th>
                <th>Üst Kategori Adı</th>
                <th>Tarih</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>

                    @if (item.UstID == 0)
                    {
                        <td>@item.Ad</td>
                    }
                    <td>@item.Tarih</td>


                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="#"><i class="btn btn-primary"></i>Düzenle</a></li>
                                    <li><a><i class="btn btn-danger"></i>Sil</a></li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
        </div>
    </div>*@

IsProjesi/IsProjesi/Views/UrunHizmet/StokHareketleri.cshtml
@{
    ViewBag.Title = "StokHareketleri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>StokHareketleri</h2>

IsProjesi/IsProjesi/Views/UrunHizmet/UrunEkleGuncelle.cshtml
@{
    ViewBag.Title = "UrunEkleGuncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    UrunHizmetKategoriBLL urunHizmetKategoriBLL = new UrunHizmetKategoriBLL();
    List<UrunHizmetKategori> urunHizmetKategoriList = urunHizmetKategoriBLL.GetAll().ToList();
    KdvBLL kdvBLL = new KdvBLL();
    List<Kdv> KdvList = kdvBLL.GetAll().ToList();

    MiktarTurBLL miktarTurBLL = new MiktarTurBLL();
    List<MiktarTur> miktarTurList = miktarTurBLL.GetAll().ToList();




}
@model UrunHizmet
<script src="~/Scripts/InotrScript/UrunHizmet.js"></script>
<div class="content-wrapper">
    <div class="page-header panel" style="padding-bottom: 0;">
        <div class="page-header-content">
            <div class="page-title">
                <h5>
                    <a href="#" class="btn bg-grey btn-icon btn-rounded btn-xs mr-10"><i class="" icon-arrow-left13"></i></a><span class="text-semibold">Urunler ve Hizmetler</span>

                </h5>
            </div>
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="UrunAdi">Başlık:</label>
                        <input type="text" class="form-control" id="UrunAdi" value="@Model.UrunAdi" placeholder="ürün adı">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="UrunTipID">Tip:</label>
                        <select class="form-control" id="UrunTipID">
                            @if (Model.ID == 0)
                            {
                                <option value="">Tip Seçiniz</option>
                            }
                            <option value="1" @(Model.UrunTipID== 1 && Model.ID > 0 ? "selected" : "" )>ürün</option>
                            <option value="0" @(Model.UrunTipID == 0 && Model.ID > 0 ? "selected" : "" )>Hizmet</option>
                        </select>
                    </div>
                </div>
               

                <div class="col-md-2">
                    <div class="form-group">
                        <label for="Kategori">Kategori:</label>

                        <select id="KategoriListe" class="form-control">
                            @foreach (UrunHizmetKategori item in urunHizmetKategoriList)
                            {
                                <option value="@item.ID" @(Model.KategoriID == item.ID ? "selected" : "")>@item.Ad</option>
                            }

                        </select>

                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="UrunKodu">Urun Kodu:</label>
                        <input type="text" class="form-control" id="UrunKodu" value="@Model.UrunKodu" placeholder="ürün kodu">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="Fiyat">Fiyatı:</label>
                        <input type="text" class="form-control" id="Fiyat" value="@Model.Fiyat" placeholder="fiyat">
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="KDV Durumu">KDV Durumu:</label>
                       
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="KDV Oran">KDV Oranı:</label>

                        <select id="KDVListe" class="form-control">
                            @foreach (Kdv item in KdvList)
                            {
                                <option value="@item.ID" @(Model.KdvID == item.ID ? "selected" : "")>@item.KdvYuzdesi</option>
                            }

                        </select>

                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="Stok Durumu">Stok Durumu:</label>

                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="Miktar Tür">Miktar Türü:</label>

                        <select id="MiktarTurListe" class="form-control">
                            @foreach (MiktarTur item in miktarTurList)
                            {
                                <option value="@item.ID" @(Model.MiktarTurD == item.ID ? "selected" : "")>@item.MiktarTurAdi</option>
                            }

                        </select>

                    </div>
                </div>
            </div>

            <div>

            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="Döngüsellik Durumu">Döngüsellik Durumu:</label>
                        
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="Döngü Aralığı">Döngü Aralığı:</label>

                        <select class="form-control" id="DonguAralik" data-live-search="true">
                            @if (Model.ID == 0)
                            {
                                <option value="">Aralık Seçiniz</option>
                            }
                            <option value="0" @(Model.UrunTipID == 0 && Model.ID > 0 ? "selected" : "" )>1 Ay</option>
                            <option value="1" @(Model.UrunTipID == 1 && Model.ID > 0 ? "selected" : "" )>2 Ay</option>
                            <option value="2" @(Model.UrunTipID == 2 && Model.ID > 0 ? "selected" : "" )>3 Ay</option>
                            <option value="3" @(Model.UrunTipID == 3 && Model.ID > 0 ? "selected" : "" )>4 Ay</option>
                            <option value="4" @(Model.UrunTipID == 4 && Model.ID > 0 ? "selected" : "" )>5 Ay</option>
                            <option value="5" @(Model.UrunTipID == 5 && Model.ID > 0 ? "selected" : "" )>6 Ay</option>
                            <option value="6" @(Model.UrunTipID == 6 && Model.ID > 0 ? "selected" : "" )>7 Ay</option>
                            <option value="7" @(Model.UrunTipID == 7 && Model.ID > 0 ? "selected" : "" )>8 Ay</option>
                            <option value="8" @(Model.UrunTipID == 8 && Model.ID > 0 ? "selected" : "" )>9 Ay</option>
                            <option value="9" @(Model.UrunTipID == 9 && Model.ID > 0 ? "selected" : "" )>10 Ay</option>
                            <option value="10" @(Model.UrunTipID == 10 && Model.ID > 0 ? "selected" : "" )>11 Ay</option>
                            <option value="11" @(Model.UrunTipID == 11 && Model.ID > 0 ? "selected" : "" )>1 Yıl</option>
                        </select>

                       
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="Döngüsel Fiyatı<">Döngüsel Fiyatı</label>
                        <input type="text" class="form-control" id="DonguselFiyat" value="@Model.DonguselFiyat" placeholder="döngüsel fiyat">
                    </div>
                </div>

            </div>

      
            <div class="row">
                @if (Model.ID == 0)
                {
                    <div class="col-md-12">

                        <a class="btn btn-success pull-right" onclick="TedarikEkle()">Ekle <i class="icon-checkmark4 position-right"></i></a>

                    </div>
                }
                else
                {
                    <div class="col-md-12">
                        <a class="btn btn-success pull-right" href="javascript:;" onclick="TedarikGuncelle(@Model.ID)">Kaydet <i class="icon-checkmark4 position-right"></i></a>
                    </div>
                }


            </div>





        </div>

    </div>
</div>

IsProjesi/IsProjesi/Views/UrunHizmet/Urunler.cshtml
@{
    ViewBag.Title = "Urunler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model List<UrunHizmet>
<div class="content-wrapper">
    <div class="panel panel-flat">
        <div class="panel-heading">

            <h5>

                <a href="urunhizmet_modul.aspx" class=""></a><span class="">Ürün &amp; Hizmetler</span>


            </h5>

            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a href="?" class="btn btn-default btn-xs"><b><i class="icon-backward"></i></b>&nbsp;GERİ</a></li>
                    <li><a href="@Url.Action("UrunEkleGuncelle","UrunHizmet")" cla class="btn btn-default btn-xs"><b><i class=" icon-plus-circle2"></i></b>&nbsp;YENİ ÜRÜN</a></li>
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>

            <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
        </div>

        <div class="panel-body">
            <div id="tablekategori_wrapper" class="dataTables_wrapper no-footer">
                <div class="datatable-scroll">
                    <table id="tableurun" class="table datatable-basic table-hover no-footer dataTable" role="grid" aria-describedby="tablekategori_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="ID: activate to sort column descending" style="width: 45px;" aria-sort="ascending">ID</th>
                                <th class="sorting_asc" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="Urun Adı: activate to sort column descending" style="width: 45px;" aria-sort="ascending">Urun Adı</th>
                                <th class="sorting" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="Kategori: activate to sort column ascending" style="width: 85px;">Kategori</th>

                                <th class="sorting" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="Tip: activate to sort column ascending" style="width: 101px;">Tip</th>
                                <th class="sorting" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="Stok Durum: activate to sort column ascending" style="width: 101px;">Stok Durum</th>
                                <th class="sorting" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="Fiyatı: activate to sort column ascending" style="width: 101px;">Fiyatı(TL)</th>
                                <th class="text-center sorting" tabindex="0" aria-controls="tableurun" rowspan="1" colspan="1" aria-label="İşlemler: activate to sort column ascending" style="width: 57px;">İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {


                                <tr role="row" class="odd">
                                    <td style="" class="sorting_1">
                                        @item.ID
                                    </td>
                                    <td style="" class="sorting_1">
                                        <span style="display:none">1500- </span>
                                        <span style="font-weight:bold">@item.UrunAdi</span>
                                    </td>
                                    <td>@item.UrunHizmetKategori.Ad</td>
                                   


                                    <td>@item.UrunTipAdi</td>
                                    <td>@item.StokDurum</td>
                                    <td>@item.Fiyat</td>
                                    <td class="text-center">
                                        <ul class="icons-list">
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                    <i class="icon-menu9"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-right">
                                                    <li onclick="UrunGuncellemeSayfasiniAc(@item.ID)"><a href="#"><i class="btn btn-primary"></i>Düzenle</a></li>
                                                    <li onclick="UruniSil(@item.ID)"><a href="#"><i class="btn btn-danger"></i>Sil</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>

            </div>


        </div>




    </div>



</div>
<script src="~/Scripts/InotrScript/UrunHizmet.js"></script>
<script>
    $(document).ready(function () {
        $('#tableurun').DataTable({

            "language": {
                "sDecimal": ",",
                "sEmptyTable": "Tabloda herhangi bir veri mevcut değil",
                "sInfo": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
                "sInfoEmpty": "Kayıt yok",
                "sInfoFiltered": "(_MAX_ kayıt içerisinden bulunan)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "Sayfada _MENU_ kayıt göster",
                "sLoadingRecords": "Yükleniyor...",
                "sProcessing": "İşleniyor...",
                "sSearch": "Ara:",
                "sZeroRecords": "Eşleşen kayıt bulunamadı",
                "oPaginate": {
                    "sFirst": "İlk",
                    "sLast": "Son",
                    "sNext": "Sonraki",
                    "sPrevious": "Önceki"
                },
                "oAria": {
                    "sSortAscending": ": artan sütun sıralamasını aktifleştir",
                    "sSortDescending": ": azalan sütun sıralamasını aktifleştir"
                }
            }


        });
    });
</script>